name: Deploy

on:
  push:
    branches:
      - dev
      - main

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Docker container for dev
        run: |
          cd lab3
          docker build -f Dockerfile.dev -t myapp-dev .
          docker run -d -p 8080:80 --name myapp-dev myapp-dev

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run Docker container for prod
        run: |
          cd lab3
          docker build -f Dockerfile.prod -t myapp-prod .
          docker run -d -p 8081:80 --name myapp-prod myapp-prod